### ISSUE TITLE
401 errors

### ISSUE THREAD

**Issue by oskarrough** [netlify/prerender#6]
Hi, when I run this repo locally and do

```
http://localhost:3000/https://www.netlify.com/
```

I get a 401 error. The tested URL doesn't seem to matter.

**Comment by Loque-** [comment]
Same... on node v8.9 here

**Comment by Loque-** [comment]
Oki, you can work around this by commenting out `server.use(prerender.basicAuth());` in server.js

My next problem is that `Set` is not supported in phantomJS... damn.

**Comment by brycekahle** [comment]
@Loque- I just merged a version that now uses headless Chrome for prerendering.

**Comment by brycekahle** [comment]
@oskarrough the change mentioned by @Loque- is necessary. You need to turn off the basic authentication.

**Comment by tommedema** [comment]
Why was this closed? Seems like there's only a workaround that requires modifying the source but there's no actual solution?

**Comment by dyelax** [comment]
I'm still having this issue and I don't see `server.use(prerender.basicAuth());` anywhere in the repo. Anyone else still facing this? node v14.8.0

**Comment by neilmispelaar** [comment]
The latest version of the `server.js` source code has the following line that you need to comment out: 

`server.use(require("./lib/plugins/basicAuth"));`
